name: Iberdrola Checker

on:
  schedule:
    - cron: "*/1 * * * *"  # Ejecuta cada minuto (puedes cambiar a 30 segundos con un loop interno)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar el script
        run: python3 check_punto_carga.py
